server:
  port: 7002

eureka:
  instance:
    hostname: localhost
  client:
    #false代表不像注册中心注册自己
    register-with-eureka: false
    #false代表自己是注册中心
    fetch-registry: false
    service-url:
      #设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://127.0.0.1:7001/eureka/
